skip_local_validator = true

[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
sss_core = "5dzttAFNMi3JNtBcBQzJWcyXwou4rN2z6KX5DitDSDHe"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
