#!/usr/bin/env bash
# Copy the Anchor-generated IDL and TypeScript types into packages/idl so the
# frontend imports them from one place instead of reaching into onchain/target.
#
# The generated directory is gitignored: it is a build artefact, and a stale
# committed copy that disagrees with the deployed program is worse than no copy.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PROGRAM="${1:-sss_core}"

IDL_SRC="$ROOT/onchain/target/idl/$PROGRAM.json"
TYPES_SRC="$ROOT/onchain/target/types/$PROGRAM.ts"
DEST="$ROOT/packages/idl/src/generated"

if [ ! -f "$IDL_SRC" ]; then
  echo "No IDL at $IDL_SRC" >&2
  echo "Run 'pnpm chain:build' first." >&2
  exit 1
fi

mkdir -p "$DEST"
cp "$IDL_SRC" "$DEST/$PROGRAM.json"
[ -f "$TYPES_SRC" ] && cp "$TYPES_SRC" "$DEST/$PROGRAM.ts"

PROGRAM_ID="$(node -e "process.stdout.write(require('$DEST/$PROGRAM.json').address ?? '')")"

# Re-export by wildcard rather than by name: Anchor derives the type name from
# the program name, and computing that in shell needs bash 4 (macOS ships 3.2).
cat > "$DEST/index.ts" <<EOF
// Generated by scripts/sync-idl.sh — do not edit.
export { default as idl } from './$PROGRAM.json' with { type: 'json' }
export * from './$PROGRAM'
export const PROGRAM_ID = '$PROGRAM_ID'
EOF

echo "Synced $PROGRAM → packages/idl/src/generated (program $PROGRAM_ID)"

if [ -n "$PROGRAM_ID" ] && [ -f "$ROOT/.env" ]; then
  ENV_PROGRAM_ID="$(grep -E '^PROGRAM_ID=' "$ROOT/.env" | cut -d= -f2- || true)"
  if [ -n "$ENV_PROGRAM_ID" ] && [ "$ENV_PROGRAM_ID" != "$PROGRAM_ID" ]; then
    echo
    echo "WARNING: .env PROGRAM_ID ($ENV_PROGRAM_ID) does not match the built program ($PROGRAM_ID)." >&2
    echo "The backend will build transactions against the wrong program." >&2
  fi
fi
